#!/bin/bash
set -e


# Run Flutter format
echo "Running Flutter format..."
flutter format .

# Run Dart analyze
echo "Running Dart analyze..."
flutter analyze

# Check outdated dependencies
echo "Checking outdated dependencies..."
flutter pub outdated --mode=null-safety

