#!/bin/bash
set -e


# Run Dart format
echo "Running Dart format..."
dart format .

# Run Dart analyze
echo "Running Dart analyze..."
flutter analyze

# Check outdated dependencies
echo "Checking outdated dependencies..."
flutter pub outdated
