name: Flutter CI

on:
  push:
    branches:
    - master
  pull_request:
    branches:
      - master

    
jobs:
  build:
    # This job will run on macos virtual machine
    runs-on: macos-latest
    steps:
    
    
    - uses: actions/checkout@v3
    # Setup Java environment in order to build the Android app.
    - uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'zulu'

   
    # Setup the flutter environment.
    - uses: subosito/flutter-action@v2
      with:
         flutter-version: '3.3.10' # you can also specify exact version of flutter
         channel: 'stable'
    
    - run: flutter doctor -v
    # Get flutter dependencies.
    - run: flutter pub get
    
    # Check for any formatting issues in the code.
    - run: flutter format --set-exit-if-changed .
    
    # Statically analyze the Dart code for any errors.
    - run: flutter analyze .
    
    # Run widget tests for our flutter project.
    #- run: flutter test
    
    # Setup android keys for signing (dummpy keys to test signing and release build for android)
    - name: create keystore
      run: printf "welcome\nwelcome\nyes\nyes\nyes\nyes\nyes\nyes\nyes" | keytool -genkey -v -keystore ./android/test.jks -keyalg RSA -keysize 2048 -validity 10000 -alias nedaa-android -storetype JKS
    - name: create key.properties
      run: printf "storePassword=welcome\nkeyPassword=welcome\nkeyAlias=nedaa-android\nstoreFile=../test.jks" > ./android/key.properties
    # Build apk.
    - run: flutter build apk
    # Build ipa.
    - run: flutter build ios --release --no-codesign
    
    # Upload generated apk to the artifacts.
    #- uses: actions/upload-artifact@v1
     # with:
      #  name: release-apk
      #  path: build/app/outputs/apk/release/app-release.apk
    - name: notification
      if: cancelled() == false
      uses: xinthink/action-telegram@v1.1
      with:
        botToken: '${{ secrets.BotToken }}'
        chatId: '${{ secrets.ChatID }}'
        jobStatus: '${{ job.status }}' 
        skipsuccess: 'false'
