name: Flutter CI

on:
  push:
    branches:
    - master
  pull_request:
    branches:
      - master

    
jobs:
  build:
    # This job will run on macos virtual machine
    runs-on: macos-latest
    steps:
    
    
    # Setup Java environment in order to build the Android app.
    - uses: actions/checkout@v1
    - uses: actions/setup-java@v1
      with:
        java-version: '12.x'
        
    - name: Cache Flutter dependencies
      uses: actions/cache@v1
      with:
        path: /opt/hostedtoolcache/flutter
        key: ${{ runner.OS }}-flutter-install-cache-3.3.10
        
    # Setup the flutter environment.
    - uses: subosito/flutter-action@v2
      with:
         flutter-version: '3.3.10' # you can also specify exact version of flutter
         channel: 'stable'
         cache: true
         cache-key: flutter # optional, change this to force refresh cache
         cache-path: ${{ runner.tool_cache }}/flutter # optional, change this to specify the cache path
         architecture: x64 # optional, x64 or arm64
    
    # Get flutter dependencies.
    - run: flutter pub get
    
    # Check for any formatting issues in the code.
    - run: flutter format --set-exit-if-changed .
    
    # Statically analyze the Dart code for any errors.
    - run: flutter analyze .
    
    # Run widget tests for our flutter project.
    #- run: flutter test
    
    # Build ipa.
    - run: flutter build ios --no-codesign
     # Build apk.
    - run: flutter build apk
    
    # Upload generated apk to the artifacts.
    #- uses: actions/upload-artifact@v1
     # with:
      #  name: release-apk
      #  path: build/app/outputs/apk/release/app-release.apk
    - name: notification
      if: cancelled() == false
      uses: xinthink/action-telegram@v1.1
      with:
        botToken: '${{ secrets.BotToken }}'
        chatId: '${{ secrets.ChatID }}'
        jobStatus: '${{ job.status }}' 
        skipsuccess: 'false'
